version: '3'

services:
    web:
        image: nginx:latest
        ports:
            - "8090:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        build:
            context: ./php
            dockerfile: Dockerfile
        depends_on:
            - mariadb
        volumes:
            - ./code:/code
        networks:
            - code-network
    mariadb:
        image: mariadb:latest
        ports:
            - "3307:3306"
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
